repos:
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.10
    hooks:
    - id: cmake-format
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v10.0.1
    hooks:
    - id: clang-format
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.4
    hooks:
    - id: autopep8