mpi_start = 'srun'
mpi_args = '-A csc359 -N 2 -n 16 -c 2 --gpus-per-task=1 --gpu-bind=closest -p batch -t 0:30:00'
testsuite_name = "SOPFLOW_frontier_ACTIVSg200"
application = 'sopflow'
iterations = 1

[presets]
hiop_verbosity_level = 0
print_output = 0
argument_list = 'log_view'

[[profiler]]

[[testcase]]
netfile = 'datafiles/case_ACTIVSg200.m'
scenfile = 'datafiles/10_scenarios_ACTIVSg200.csv'
ctgfile = 'datafiles/case_ACTIVSg200.cont'
sopflow_Ns = 10
sopflow_Nc = 9999
sopflow_solver = 'HIOP'
sopflow_subproblem_model = 'PBPOLRAJAHIOP'
sopflow_subproblem_solver = 'HIOP'
hiop_compute_mode = 'GPU'
hiop_mem_space = 'DEVICE'
opflow_initialization = 'FROMFILE'
opflow_ignore_lineflow_constraints = 1
opflow_include_powerimbalance_variables = 0
opflow_include_loadloss_variables = 0
opflow_tolerance = 1e-6
opflow_output_format = 'MINIMAL'
sopflow_enable_multicontingency = 0
sopflow_flatten_contingencies = 1
save_output = 1
sopflow_output_directory = 'performance_analysis/profile_dumps'
hiop_mu0 = 1e-1
hiop_fixed_var = 'relax'
hiop_tolerance = 1e-6
hiop_linsol_mode = 'forcequick'
hiop_scaling_type = 'none'
hiop_ir_outer_maxit = 0
hiop_time_kkt = 'on'
