include:
  - local: '.gitlab/pnnl/base.gitlab-ci.yml'

.deception:
  rules:
    - *rule_no_newell_rebuild
    - *rule_no_deception_rebuild
    - *rule_no_ascent_rebuild
    - *rule_no_incline_rebuild
    - *rule_no_newell_test
    - *rule_no_incline_test
    - *rule_no_ascent_test
    - *rule_1
    - *rule_2
    - *rule_3
  variables:
    MY_CLUSTER: "deception"
    WORKDIR_SUFFIX: "x86_64-gcc-cuda-build"
    SLURM_ARGS: " --gres=gpu:1 --ntasks=3 "

Deception Build:
  extends:
    - .cluster_build
    - .deception
  variables:
    SCRIPT_ARGS: " --build-only --job=gcc-cuda "

Deception Test:
  extends:
    - .cluster_test
    - .deception
  variables:
    CTESTARGS: " --timeout 240 --output-on-failure -E Python -LE deception-skip "
    SCRIPT_ARGS: " --test-only --job=gcc-cuda "
  needs: ['Deception Build']

Deception Py Test:
  extends:
    - .cluster_py_test
    - .deception
  variables:
    SCRIPT_ARGS: " --test-only --job=gcc-cuda "
  needs: ['Deception Build']

Deception Module Rebuild:
  extends: .module_rebuild
  rules:
    - if: '$CI_COMMIT_TITLE =~ /\[deception-rebuild\]/'
      when: always
    - when: manual
  variables:
    MY_CLUSTER: "deception"
    WORKDIR_SUFFIX: "spack_deception"
  
cleanup:
  stage: .pre
  extends: .SVC-Account-Cleanup

pending:
  variables:
    MY_CLUSTER: "Deception"
  extends:
    - .report-pending
  stage: .pre

success:
  variables:
    MY_CLUSTER: "Deception"
  extends:
    - .report-status
  stage: .post
       
failure:
  stage: .post
  variables:
    MY_CLUSTER: "Deception"
  extends:
    - .report-status
  rules:
    - when: on_failure