#!/bin/bash

#SBATCH --nodes=4
#SBATCH -n 16
#SBATCH --job-name=exago_4
#SBATCH --gpu-bind=closest
#SBATCH --gpus-per-task=1
#SBATCH --cpus-per-task=1
#SBATCH --output=profile_frontier_4.%J
#SBATCH --time=0:30:00
#SBATCH --error=profile_frontier_4.%J
#SBATCH -A CSC359
#SBATCH -p batch
#SBATCH -C nvme

#SBATCH --mail-type=END
#SBATCH --mail-user=sayefsakin@gmail.com

source buildsystem/clang-hip/frontierVariables.sh
source buildsystem/spack/frontier/modules/exago.sh


srun -A csc359 -N 4 -n 16 -c 1 --gpus-per-task=1 --gpu-bind=closest \
-p batch -t 0:30:00 --job-name=exago_perf_run \
sopflow -print_output 1 -log_view \
-netfile datafiles/case_ACTIVSg200.m \
-scenfile datafiles/10_scenarios_ACTIVSg200.csv \
-ctgfile datafiles/case_ACTIVSg200.cont \
-sopflow_Ns 10 -sopflow_Nc 9999 \
-opflow_initialization FROMFILE \
-opflow_ignore_lineflow_constraints 1 \
-opflow_include_powerimbalance_variables 0 \
-opflow_include_loadloss_variables 0 \
-opflow_tolerance 1e-06 \
-sopflow_flatten_contingencies 1 \
-save_output 1 \
-sopflow_output_directory performance_analysis/profile_dumps \
-hiop_mem_space DEVICE \
-opflow_output_format MINIMAL \
-sopflow_solver HIOP \
-sopflow_subproblem_solver HIOP \
-sopflow_subproblem_model PBPOLRAJAHIOP \
-sopflow_enable_multicontingency 0 \
