services:
  proxy:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    restart: always
  frontend:
    container_name: node
    build: .
    ports:
      - "8080:8080"
    restart: always
  backend:
    container_name: flask
    build: ./backend
    ports:
      - "5000:5000"
    # links:
    #   - "database:localhost"
    restart: always
  database:
    container_name: postgres
    image: postgis/postgis:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=CHANGEME
    volumes:
      - ./data:/mnt
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: always
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@admin.com
      - PGADMIN_DEFAULT_PASSWORD=CHANGEME
    ports:
      - "5050:80"
    depends_on:
      - database
    restart: always
  # ollama:
