services:
  frontend:
    container_name: node
    build: .
    ports:
      - "8080:8080"
    restart: always
  backend:
    container_name: flask
    build: ./backend
    ports:
      - "5000:5000"
    env_file: 
      - setup.env
    restart: always
  database:
    container_name: postgres
    image: postgis/postgis:latest
    volumes:
      - ./data:/mnt
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    env_file:
      - setup.env
    restart: always
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    depends_on:
      - database
    env_file: 
      - setup.env
    restart: always
  # ollama: