spack:
  specs:
  - openmpi
  - petsc
  - ipopt
  - suite-sparse
  - umpire
  - raja
  view: true
  definitions:
  - compilers: [gcc@8.4.1]
  compilers:
  - compiler:
      spec: gcc@8.4.1
      paths:
        cc: gcc
        cxx: g++
        f77: gfortran
        fc: gfortran
      flags: {}
      operating_system: centos8
      target: any
      modules: []
      environment: {}
      extra_rpaths: []
  packages:
    umpire:
      variants: ~examples+openmp
    raja:
      variants: ~examples~exercises
    ipopt:
      variants: ~mumps+metis+coinhsl
    coinhsl:
      variants: +blas
    petsc:
      variants: +mpi~mumps+shared
      version: [3.14.1]
    suite-sparse:
      version: [5.8.1]
    umpire:
      version: [4.1.2]
    cmake:
      externals:
      - spec: cmake
        prefix: /usr
      buildable: false
    openblas:
      externals:
      - spec: openblas
        prefix: /usr
      buildable: false
    openmpi:
      externals:
      - spec: openmpi
        prefix: /usr/lib64/openmpi
      buildable: false
    python:
      externals:
      - spec: python@3.6.8
        prefix: /usr
      buildable: false
    openssl:
      externals:
      - spec: openssl
        prefix: /usr
      buildable: false
    diffutils:
      externals:
      - spec: diffutils
        prefix: /usr
      buildable: false
    pkgconf:
      externals:
      - spec: pkgconf
        prefix: /usr
      buildable: false
    perl:
      externals:
      - spec: perl
        prefix: /usr
      buildable: false
    mpfr:
      externals:
      - spec: mpfr
        prefix: /usr
      buildable: false
    hdf5:
      externals:
      - spec: hdf5
        prefix: /usr/lib64/openmpi
      buildable: false
    zlib:
      externals:
      - spec: zlib
        prefix: /usr
      buildable: false
    m4:
      externals:
      - spec: m4
        prefix: /usr
      buildable: false
    gmp:
      externals:
      - spec: gmp
        prefix: /usr
      buildable: false
    suite-sparse:
      externals:
      - spec: suite-sparse
        prefix: /usr
      buildable: false
    make:
      externals:
      - spec: make
        prefix: /usr
      buildable: false
