name: file-naming-conventions

on: [push]

jobs:
    naming-conventions:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - uses: shogo82148/actions-setup-perl@v1
          with:
            perl-version: '5.34'
        - run: ./buildsystem/tools/file_naming_conventions.pl
