name: Mirroring

# triggers a github action everytime there is a push or mr
on: [pull_request]

jobs:
  # To test on HPC resources we must first mirror the repo and then trigger a pipeline
  to_pnnl_gitlab:
     # Latest Ubuntu as of Feb 2023 is 20.04
     runs-on: ubuntu-22.04
     steps:
       # Action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
       - uses: actions/checkout@v1
       #  Action for mirroring your commits to a different remote repository
       - uses: yesolutions/mirror-action@master
       # Give actions access to some secrets
         with:
            GIT_PUSH_ARGS: '--tags --force'
            REMOTE: 'https://gitlab.pnnl.gov/exasgd/frameworks/exago-github-mirror'
            GIT_USERNAME:  ${{ secrets.GIT_USER }}
            GIT_PASSWORD:  ${{ secrets.GIT_PASSWORD }}

       - name: Trigger Pipeline
         run: |
          curl -X POST -F token=${{ secrets.PNNL_PIPELINE_TRIGGER }} -F ref=${{ github.head_ref }} https://gitlab.pnnl.gov/api/v4/projects/1619/trigger/pipeline
          exit $?
