name: pre-commit

# Won't run on develop/main directly
on: [pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0
    - uses: EndBug/add-and-commit@v9.1.3
      # Only need to try and commit if the action failed
      if: failure()
      with:
        fetch: false
        committer_name: GitHub Actions
        committer_email: actions@github.com
        message: Apply pre-commmit fixes 
        
