# https://spack.readthedocs.io/en/latest/binary_caches.html#spack-build-cache-for-github-actions
name: Spack Ubunutu x86_64 Buildcache

env:
  SPACK_COLOR: always
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  USERNAME: exago-bot

# Until we remove the need to clone submodules to build, this should on be in PRs
on: [pull_request]

jobs:
  base_image_build:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read

    name: Build Custom Base Image
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Once we move submodule deps into spack, we can do some more builds
          # Also need to change build script to use spack from base image
          submodules: true

      # Need to build custom base image with gfortran
      - name: Create Dockerfile heredoc
        run: |
          cat << EOF > Dockerfile
          FROM ubuntu:22.04
          LABEL oci.opencontainers.image.base.name="ubuntu-22.04-fortran"
          RUN apt-get update && apt-get install -y --no-install-recommends \
              gfortran \
              && rm -rf /var/lib/apt/lists/*
          EOF

      # https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker base image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  
  exago_spack_builds:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read
    
    strategy:
      matrix:
        # Minimal Build(s) - GHCR mirror speeds these up a lot!
        spack_spec:
          # See #39 - ~python~mpi causes issues
        # - exago@develop~mpi~ipopt~hiop~python~raja
          # See #44 - +mpi~python should fail if no python in system,
          #                       but the runner happens to have one...
          - exago@1.6.0+mpi~ipopt+hiop~python~raja ^openmpi
          # See #18 - +hiop~mpi causes issues
        # - exago@develop~mpi~ipopt+hiop~python+raja
          # See #16 - +python~mpi causes issues
        # - exago@develop~mpi~ipopt+hiop+python~raja
          - exago@1.6.0+mpi~ipopt+hiop+python~raja ^openmpi
          # See #40 - +hiop+raja~ipopt ^hiop~sparse is useful for edge cases
          - exago@1.6.0+mpi~ipopt+hiop~python+raja ^openmpi ^hiop+raja~sparse 

    name: Build ExaGO with Spack
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Once we move submodule deps into spack, we can do some more builds
          # Also need to change build script to use spack from base image
          submodules: true
      
      - name: Setup Spack
        run: echo "$PWD/tpl/spack/bin" >> "$GITHUB_PATH"
      
      - name: Create heredoc spack.yaml
        run: |
          cat << EOF > spack.yaml
          spack:
            specs:
            - ${{ matrix.spack_spec }}
            concretizer:
              unify: true
              reuse: true
            config:
              install_tree:
                root: /opt/spack
                padded_length: 128
            packages:
              all:
                require: target=x86_64_v2
            mirrors:
              local-buildcache: oci://ghcr.io/pnnl/ExaGO
              spack: https://binaries.spack.io/develop

      - name: Configure GHCR mirror
        run: spack -e . mirror set --oci-username ${{ env.USERNAME }} --oci-password "${{ secrets.GITHUB_TOKEN }}" local-buildcache
      
      - name: Trust keys
        run: spack -e . buildcache keys --install --trust
      
      - name: Find external packages
        run: spack -e . external find --all --exclude python

      - name: Concretize
        run: spack -e . concretize
  
      - name: Install
        run: spack -e . install --no-check-signature

      - name: Push to binaries to buildcache
        run: |
          spack -e . buildcache push --base-image ghcr.io/pnnl/exago:ubuntu-22.04-gfortran --unsigned --update-index local-buildcache
        if: ${{ !cancelled() }}
